// <auto-generated />
namespace DataObjects.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class NewWithData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewWithData));
        
        string IMigrationMetadata.Id
        {
            get { return "201307280137067_NewWithData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
